# Generated by Django 2.2.1 on 2019-06-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mustmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
