# Generated by Django 2.2.1 on 2019-06-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_mustmodel_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mustmodel',
            name='active',
        ),
        migrations.AddField(
            model_name='mustmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
