# Generated by Django 2.2.1 on 2019-06-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190607_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=0, max_digits=3)),
                ('version_title', models.CharField(max_length=50)),
                ('aggregated_rating', models.DecimalField(decimal_places=0, max_digits=3)),
                ('summary', models.CharField(max_length=500)),
                ('first_release_date', models.DateField()),
                ('rating_count', models.DecimalField(decimal_places=0, max_digits=3)),
                ('aggregated_rating_count', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PlatformModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenshotGameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.GameModel')),
                ('screenshot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ImageModel')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformGameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.GameModel')),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.PlatformModel')),
            ],
        ),
        migrations.CreateModel(
            name='GenreGameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.GameModel')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.GenreModel')),
            ],
        ),
        migrations.CreateModel(
            name='CoverGameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ImageModel')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.GameModel')),
            ],
        ),
    ]
