# Generated by Django 2.2.1 on 2019-06-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190610_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='version_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
