# Generated by Django 2.2.1 on 2019-06-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20190610_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covergamemodel',
            old_name='cover_id',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='covergamemodel',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='genregamemodel',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='genregamemodel',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='platformgamemodel',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='platformgamemodel',
            old_name='platform_id',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='screenshotgamemodel',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='screenshotgamemodel',
            old_name='screenshot_id',
            new_name='screenshot',
        ),
    ]
