# Generated by Django 2.2.1 on 2019-06-10 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20190610_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.IntegerField()),
                ('is_cover', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='unique_img',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.UniqueImageModel'),
            preserve_default=False,
        ),
    ]
