# Generated by Django 2.2.1 on 2019-06-10 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20190610_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ScreenshotModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='covergamemodel',
            name='cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.CoverModel'),
        ),
        migrations.AlterField(
            model_name='screenshotgamemodel',
            name='screenshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ScreenshotModel'),
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.DeleteModel(
            name='UniqueImageModel',
        ),
    ]
