# Generated by Django 2.2.1 on 2019-06-11 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20190610_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('rating', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
                ('version_title', models.CharField(max_length=100, null=True)),
                ('aggregated_rating', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
                ('summary', models.CharField(max_length=2500, null=True)),
                ('first_release_date', models.DateField(null=True)),
                ('rating_count', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
                ('aggregated_rating_count', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('games', models.ManyToManyField(related_name='genres', to='main_app.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Must',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('games', models.ManyToManyField(related_name='platforms', to='main_app.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='main_app.Game')),
            ],
        ),
        migrations.RemoveField(
            model_name='genregamemodel',
            name='game',
        ),
        migrations.RemoveField(
            model_name='genregamemodel',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='mustmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='platformgamemodel',
            name='game',
        ),
        migrations.RemoveField(
            model_name='platformgamemodel',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='screenshotgamemodel',
            name='game',
        ),
        migrations.RemoveField(
            model_name='screenshotgamemodel',
            name='screenshot',
        ),
        migrations.DeleteModel(
            name='CoverGameModel',
        ),
        migrations.DeleteModel(
            name='CoverModel',
        ),
        migrations.DeleteModel(
            name='GameModel',
        ),
        migrations.DeleteModel(
            name='GenreGameModel',
        ),
        migrations.DeleteModel(
            name='GenreModel',
        ),
        migrations.DeleteModel(
            name='MustModel',
        ),
        migrations.DeleteModel(
            name='PlatformGameModel',
        ),
        migrations.DeleteModel(
            name='PlatformModel',
        ),
        migrations.DeleteModel(
            name='ScreenshotGameModel',
        ),
        migrations.DeleteModel(
            name='ScreenshotModel',
        ),
        migrations.AddField(
            model_name='cover',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='main_app.Game'),
        ),
    ]
