# Generated by Django 2.2.1 on 2019-06-11 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20190611_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='main_app.Game'),
        ),
    ]
