# Generated by Django 2.2.1 on 2019-06-11 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20190611_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['rating']},
        ),
    ]
