# Generated by Django 2.2.1 on 2019-06-12 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20190611_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='must',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musts', to='main_app.Game'),
        ),
    ]
